FROM golang:tip-bookworm AS builder
WORKDIR /app
COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod download
COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o ./redis-go ./app/*.go

FROM alpine:3.23.3 AS runner
WORKDIR /app
COPY --from=builder /app/redis-go ./
CMD [ "/app/redis-go" ]
