// Code generated by cmdgen. DO NOT EDIT.

package credis

import (
	"fmt"
	"strconv"
	"strings"
	"time"
)

type Cmd string

const (
	ECHO        = "echo"
	COMMAND     = "command"
	PING        = "ping"
	SET         = "set"
	GET         = "get"
	INCR        = "incr"
	MULTI       = "multi"
	EXEC        = "exec"
	DISCARD     = "discard"
	INFO        = "info"
	REPLCONF    = "replconf"
	PSYNC       = "psync"
	CONFIG      = "config"
	KEYS        = "keys"
	XADD        = "xadd"
	TYPE        = "type"
	RPUSH       = "rpush"
	LRANGE      = "lrange"
	LPUSH       = "lpush"
	LLEN        = "llen"
	LPOP        = "lpop"
	BLPOP       = "blpop"
	WAIT        = "wait"
	SUBSCRIBE   = "subscribe"
	UNSUBSCRIBE = "unsubscribe"
	QUIT        = "quit"
	PUBLISH     = "publish"
	ACL_WHOAMI  = "acl_whoami"
	ACL_GETUSER = "acl_getuser"
	ACL_SETUSER = "acl_setuser"
	AUTH        = "auth"
	ZADD        = "zadd"
	ZRANK       = "zrank"
	ZRANGE      = "zrange"
	ZCARD       = "zcard"
	ZSCORE      = "zscore"
	ZREM        = "zrem"
	WATCH       = "watch"
	UNWATCH     = "unwatch"
	GEOADD      = "geoadd"
	GEOPOS      = "geopos"
)

var commandRegistry = map[string]GenericSpec{
	ECHO: {
		MinArgs:   1,
		MaxArgs:   -1,
		Supported: true,
	},
	COMMAND: {
		MinArgs:   1,
		MaxArgs:   -1,
		Supported: true,
	},
	PING: {
		MinArgs:   0,
		MaxArgs:   0,
		Supported: true,
	},
	SET: {
		MinArgs:   2,
		MaxArgs:   4,
		Supported: true,
	},
	GET: {
		MinArgs:   1,
		MaxArgs:   1,
		Supported: true,
	},
	INCR: {
		MinArgs:   1,
		MaxArgs:   1,
		Supported: true,
	},
	MULTI: {
		MinArgs:   0,
		MaxArgs:   0,
		Supported: true,
	},
	EXEC: {
		MinArgs:   0,
		MaxArgs:   0,
		Supported: true,
	},
	DISCARD: {
		MinArgs:   0,
		MaxArgs:   0,
		Supported: true,
	},
	INFO: {
		MinArgs:   1,
		MaxArgs:   1,
		Supported: true,
	},
	REPLCONF: {
		MinArgs:   2,
		MaxArgs:   2,
		Supported: true,
	},
	PSYNC: {
		MinArgs:   2,
		MaxArgs:   2,
		Supported: true,
	},
	CONFIG: {
		MinArgs:   2,
		MaxArgs:   2,
		Supported: true,
	},
	KEYS: {
		MinArgs:   1,
		MaxArgs:   1,
		Supported: true,
	},
	XADD: {
		MinArgs:   4,
		MaxArgs:   -1,
		Supported: true,
	},
	TYPE: {
		MinArgs:   1,
		MaxArgs:   1,
		Supported: true,
	},
	RPUSH: {
		MinArgs:   2,
		MaxArgs:   -1,
		Supported: true,
	},
	LRANGE: {
		MinArgs:   3,
		MaxArgs:   3,
		Supported: true,
	},
	LPUSH: {
		MinArgs:   2,
		MaxArgs:   -1,
		Supported: true,
	},
	LLEN: {
		MinArgs:   1,
		MaxArgs:   1,
		Supported: true,
	},
	LPOP: {
		MinArgs:   1,
		MaxArgs:   2,
		Supported: true,
	},
	BLPOP: {
		MinArgs:   1,
		MaxArgs:   -1,
		Supported: true,
	},
	WAIT: {
		MinArgs:   2,
		MaxArgs:   2,
		Supported: true,
	},
	SUBSCRIBE: {
		MinArgs:   1,
		MaxArgs:   1,
		Supported: true,
	},
	UNSUBSCRIBE: {
		MinArgs:   1,
		MaxArgs:   1,
		Supported: true,
	},
	QUIT: {
		MinArgs:   0,
		MaxArgs:   0,
		Supported: true,
	},
	PUBLISH: {
		MinArgs:   2,
		MaxArgs:   2,
		Supported: true,
	},
	ACL_WHOAMI: {
		MinArgs:   0,
		MaxArgs:   0,
		Supported: true,
	},
	ACL_GETUSER: {
		MinArgs:   1,
		MaxArgs:   1,
		Supported: true,
	},
	ACL_SETUSER: {
		MinArgs:   2,
		MaxArgs:   -1,
		Supported: true,
	},
	AUTH: {
		MinArgs:   2,
		MaxArgs:   2,
		Supported: true,
	},
	ZADD: {
		MinArgs:   3,
		MaxArgs:   3,
		Supported: true,
	},
	ZRANK: {
		MinArgs:   2,
		MaxArgs:   2,
		Supported: true,
	},
	ZRANGE: {
		MinArgs:   3,
		MaxArgs:   3,
		Supported: true,
	},
	ZCARD: {
		MinArgs:   1,
		MaxArgs:   1,
		Supported: true,
	},
	ZSCORE: {
		MinArgs:   2,
		MaxArgs:   2,
		Supported: true,
	},
	ZREM: {
		MinArgs:   2,
		MaxArgs:   2,
		Supported: true,
	},
	WATCH: {
		MinArgs:   1,
		MaxArgs:   -1,
		Supported: true,
	},
	UNWATCH: {
		MinArgs:   0,
		MaxArgs:   0,
		Supported: true,
	},
	GEOADD: {
		MinArgs:   4,
		MaxArgs:   4,
		Supported: true,
	},
	GEOPOS: {
		MinArgs:   1,
		MaxArgs:   -1,
		Supported: true,
	},
}

type FullParser interface {
	Parse(args ...Token) error
}

type ScalerParser interface {
	ParseScaler(args ...Token) (int, error)
}

type FlagParser interface {
	ParseFlags(args ...Token) error
}

type VariadicTailParser interface {
	ParseTail(args ...Token) error
}

func notImplemented(cmd string) Response {
	return &response{
		data: NewEncoder().SimpleError(fmt.Sprintf("ERR %v: Not Implemented", cmd)),
	}
}

type Specs interface {
	String() string
}

type GenericSpec struct {
	MinArgs   int
	MaxArgs   int
	Supported bool
}

func GetGenericSpec(cmd string) GenericSpec {
	return commandRegistry[cmd]
}

func ParseCmd(tkns ...Token) (int, string, error) {
	argsIndex := 1
	var c string
	c = strings.ToLower(tkns[0].Literal.(string))
	if c == "acl" && len(tkns) >= 2 {
		subcmd := strings.ToLower(tkns[1].Literal.(string))
		c = c + "_" + subcmd
		argsIndex = 2
	}
	if !commandRegistry[c].Supported {
		return 0, "", fmt.Errorf("ERR unsupported command")
	}
	return argsIndex, c, nil
}

type ECHOSpecs struct {
	Data string
}

func (s *ECHOSpecs) String() string {
	return ECHO
}

type COMMANDSpecs struct {
}

func (s *COMMANDSpecs) String() string {
	return COMMAND
}

type PINGSpecs struct {
}

func (s *PINGSpecs) String() string {
	return PING
}

type SETSpecs struct {
	Key   string
	Value Token
	Px    *uint64
}

func (s *SETSpecs) String() string {
	return SET
}
func (s *SETSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	s.Value = args[1]

	return 2, nil
}

type GETSpecs struct {
	Key         string
	CurrentTime time.Time
}

func (s *GETSpecs) String() string {
	return GET
}
func (s *GETSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	s.CurrentTime = time.Now()
	return 1, nil
}

type INCRSpecs struct {
	Key         string
	CurrentTime time.Time
}

func (s *INCRSpecs) String() string {
	return INCR
}
func (s *INCRSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	s.CurrentTime = time.Now()
	return 1, nil
}

type MULTISpecs struct {
}

func (s *MULTISpecs) String() string {
	return MULTI
}

type EXECSpecs struct {
}

func (s *EXECSpecs) String() string {
	return EXEC
}

type DISCARDSpecs struct {
}

func (s *DISCARDSpecs) String() string {
	return DISCARD
}

type INFOSpecs struct {
	Section string
}

func (s *INFOSpecs) String() string {
	return INFO
}
func (s *INFOSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Section = strVal0

	return 1, nil
}

type REPLCONFSpecs struct {
	ListeningPort *string
	Capability    *string
	GetAck        *string
}

func (s *REPLCONFSpecs) String() string {
	return REPLCONF
}

type PSYNCSpecs struct {
	ReplicaId string
	Offset    string
}

func (s *PSYNCSpecs) String() string {
	return PSYNC
}
func (s *PSYNCSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.ReplicaId = strVal0

	strVal1 := args[1].Literal.(string)
	s.Offset = strVal1

	return 2, nil
}

type CONFIGSpecs struct {
	Action string
	Key    string
}

func (s *CONFIGSpecs) String() string {
	return CONFIG
}
func (s *CONFIGSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Action = strVal0

	strVal1 := args[1].Literal.(string)
	s.Key = strVal1

	return 2, nil
}

type KEYSSpecs struct {
	Filter string
}

func (s *KEYSSpecs) String() string {
	return KEYS
}
func (s *KEYSSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Filter = strVal0

	return 1, nil
}

type XADDSpecs struct {
	Key string
	Id  *int64
	Seq *int64
	KVs []KeyValue
}

func (s *XADDSpecs) String() string {
	return XADD
}

type TYPESpecs struct {
	Key         string
	CurrentTime time.Time
}

func (s *TYPESpecs) String() string {
	return TYPE
}
func (s *TYPESpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	s.CurrentTime = time.Now()
	return 1, nil
}

type RPUSHSpecs struct {
	Key      string
	Elements []string
}

func (s *RPUSHSpecs) String() string {
	return RPUSH
}
func (s *RPUSHSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	s.Elements = make([]string, 0)
	for _, el := range args[1:] {
		s.Elements = append(s.Elements, el.Literal.(string))
	}

	return 2, nil
}

type LRANGESpecs struct {
	Key   string
	Start int64
	End   int64
}

func (s *LRANGESpecs) String() string {
	return LRANGE
}
func (s *LRANGESpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	if parsed, err := strconv.ParseInt(args[1].Literal.(string), 10, 64); err != nil {
		return 0, err
	} else {
		intVal1 := parsed
		s.Start = intVal1
	}

	if parsed, err := strconv.ParseInt(args[2].Literal.(string), 10, 64); err != nil {
		return 0, err
	} else {
		intVal2 := parsed
		s.End = intVal2
	}

	return 3, nil
}

type LPUSHSpecs struct {
	Key      string
	Elements []string
}

func (s *LPUSHSpecs) String() string {
	return LPUSH
}
func (s *LPUSHSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	s.Elements = make([]string, 0)
	for _, el := range args[1:] {
		s.Elements = append(s.Elements, el.Literal.(string))
	}

	return 2, nil
}

type LLENSpecs struct {
	Key string
}

func (s *LLENSpecs) String() string {
	return LLEN
}
func (s *LLENSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	return 1, nil
}

type LPOPSpecs struct {
	Key            string
	AmountToRemove *int64
}

func (s *LPOPSpecs) String() string {
	return LPOP
}
func (s *LPOPSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	if len(args) > 1 {
		if parsed, err := strconv.ParseInt(args[1].Literal.(string), 10, 64); err != nil {
			return 0, err
		} else {
			intVal1 := parsed
			s.AmountToRemove = &intVal1
		}

	}

	return 2, nil
}

type BLPOPSpecs struct {
	Keys      []string
	Lifetime  *float64
	Concluded bool
}

func (s *BLPOPSpecs) String() string {
	return BLPOP
}

type WAITSpecs struct {
	NumReplicas uint64
	Timeout     uint64
}

func (s *WAITSpecs) String() string {
	return WAIT
}
func (s *WAITSpecs) ParseScaler(args ...Token) (int, error) {
	if parsed, err := strconv.ParseUint(args[0].Literal.(string), 10, 64); err != nil {
		return 0, err
	} else {
		uintVal0 := parsed
		s.NumReplicas = uintVal0
	}

	if parsed, err := strconv.ParseUint(args[1].Literal.(string), 10, 64); err != nil {
		return 0, err
	} else {
		uintVal1 := parsed
		s.Timeout = uintVal1
	}

	return 2, nil
}

type SUBSCRIBESpecs struct {
	Key string
}

func (s *SUBSCRIBESpecs) String() string {
	return SUBSCRIBE
}
func (s *SUBSCRIBESpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	return 1, nil
}

type UNSUBSCRIBESpecs struct {
	Key string
}

func (s *UNSUBSCRIBESpecs) String() string {
	return UNSUBSCRIBE
}
func (s *UNSUBSCRIBESpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	return 1, nil
}

type QUITSpecs struct {
}

func (s *QUITSpecs) String() string {
	return QUIT
}

type PUBLISHSpecs struct {
	Key     string
	Message string
}

func (s *PUBLISHSpecs) String() string {
	return PUBLISH
}
func (s *PUBLISHSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	strVal1 := args[1].Literal.(string)
	s.Message = strVal1

	return 2, nil
}

type ACL_WHOAMISpecs struct {
}

func (s *ACL_WHOAMISpecs) String() string {
	return ACL_WHOAMI
}

type ACL_GETUSERSpecs struct {
	User string
}

func (s *ACL_GETUSERSpecs) String() string {
	return ACL_GETUSER
}
func (s *ACL_GETUSERSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.User = strVal0

	return 1, nil
}

type ACL_SETUSERSpecs struct {
	Username string
	Rules    []string
}

func (s *ACL_SETUSERSpecs) String() string {
	return ACL_SETUSER
}
func (s *ACL_SETUSERSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Username = strVal0

	s.Rules = make([]string, 0)
	for _, el := range args[1:] {
		s.Rules = append(s.Rules, el.Literal.(string))
	}

	return 2, nil
}

type AUTHSpecs struct {
	Username string
	Password string
}

func (s *AUTHSpecs) String() string {
	return AUTH
}
func (s *AUTHSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Username = strVal0

	strVal1 := args[1].Literal.(string)
	s.Password = strVal1

	return 2, nil
}

type ZADDSpecs struct {
	Key   string
	Score float64
	Value string
}

func (s *ZADDSpecs) String() string {
	return ZADD
}
func (s *ZADDSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	if parsed, err := strconv.ParseFloat(args[1].Literal.(string), 64); err != nil {
		return 0, err
	} else {
		floatVal1 := parsed
		s.Score = floatVal1
	}

	strVal2 := args[2].Literal.(string)
	s.Value = strVal2

	return 3, nil
}

type ZRANKSpecs struct {
	Key   string
	Value string
}

func (s *ZRANKSpecs) String() string {
	return ZRANK
}
func (s *ZRANKSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	strVal1 := args[1].Literal.(string)
	s.Value = strVal1

	return 2, nil
}

type ZRANGESpecs struct {
	Key   string
	Start int64
	End   int64
}

func (s *ZRANGESpecs) String() string {
	return ZRANGE
}
func (s *ZRANGESpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	if parsed, err := strconv.ParseInt(args[1].Literal.(string), 10, 64); err != nil {
		return 0, err
	} else {
		intVal1 := parsed
		s.Start = intVal1
	}

	if parsed, err := strconv.ParseInt(args[2].Literal.(string), 10, 64); err != nil {
		return 0, err
	} else {
		intVal2 := parsed
		s.End = intVal2
	}

	return 3, nil
}

type ZCARDSpecs struct {
	Key string
}

func (s *ZCARDSpecs) String() string {
	return ZCARD
}
func (s *ZCARDSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	return 1, nil
}

type ZSCORESpecs struct {
	Key   string
	Value string
}

func (s *ZSCORESpecs) String() string {
	return ZSCORE
}
func (s *ZSCORESpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	strVal1 := args[1].Literal.(string)
	s.Value = strVal1

	return 2, nil
}

type ZREMSpecs struct {
	Key   string
	Value string
}

func (s *ZREMSpecs) String() string {
	return ZREM
}
func (s *ZREMSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	strVal1 := args[1].Literal.(string)
	s.Value = strVal1

	return 2, nil
}

type WATCHSpecs struct {
	Keys []string
}

func (s *WATCHSpecs) String() string {
	return WATCH
}
func (s *WATCHSpecs) ParseScaler(args ...Token) (int, error) {
	s.Keys = make([]string, 0)
	for _, el := range args[0:] {
		s.Keys = append(s.Keys, el.Literal.(string))
	}

	return 1, nil
}

type UNWATCHSpecs struct {
}

func (s *UNWATCHSpecs) String() string {
	return UNWATCH
}

type GEOADDSpecs struct {
	Key    string
	Lng    float64
	Lat    float64
	Member string
}

func (s *GEOADDSpecs) String() string {
	return GEOADD
}
func (s *GEOADDSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	if parsed, err := strconv.ParseFloat(args[1].Literal.(string), 64); err != nil {
		return 0, err
	} else {
		floatVal1 := parsed
		s.Lng = floatVal1
	}

	if parsed, err := strconv.ParseFloat(args[2].Literal.(string), 64); err != nil {
		return 0, err
	} else {
		floatVal2 := parsed
		s.Lat = floatVal2
	}

	strVal3 := args[3].Literal.(string)
	s.Member = strVal3

	return 4, nil
}

type GEOPOSSpecs struct {
	Key  string
	Locs []string
}

func (s *GEOPOSSpecs) String() string {
	return GEOPOS
}
func (s *GEOPOSSpecs) ParseScaler(args ...Token) (int, error) {
	strVal0 := args[0].Literal.(string)
	s.Key = strVal0

	s.Locs = make([]string, 0)
	for _, el := range args[1:] {
		s.Locs = append(s.Locs, el.Literal.(string))
	}

	return 2, nil
}

func ParseSpec(cmd string, args ...Token) (specs Specs, err error) {
	spec := GetGenericSpec(cmd)
	if len(args) < spec.MinArgs || (spec.MaxArgs >= 0 && len(args) > spec.MaxArgs) {
		err = fmt.Errorf("ERR wrong number of arguments for '%s' command", cmd)
		return
	}
	switch cmd {
	case ECHO:
		specs = &ECHOSpecs{}
	case COMMAND:
		specs = &COMMANDSpecs{}
	case PING:
		specs = &PINGSpecs{}
	case SET:
		specs = &SETSpecs{}
	case GET:
		specs = &GETSpecs{}
	case INCR:
		specs = &INCRSpecs{}
	case MULTI:
		specs = &MULTISpecs{}
	case EXEC:
		specs = &EXECSpecs{}
	case DISCARD:
		specs = &DISCARDSpecs{}
	case INFO:
		specs = &INFOSpecs{}
	case REPLCONF:
		specs = &REPLCONFSpecs{}
	case PSYNC:
		specs = &PSYNCSpecs{}
	case CONFIG:
		specs = &CONFIGSpecs{}
	case KEYS:
		specs = &KEYSSpecs{}
	case XADD:
		specs = &XADDSpecs{}
	case TYPE:
		specs = &TYPESpecs{}
	case RPUSH:
		specs = &RPUSHSpecs{}
	case LRANGE:
		specs = &LRANGESpecs{}
	case LPUSH:
		specs = &LPUSHSpecs{}
	case LLEN:
		specs = &LLENSpecs{}
	case LPOP:
		specs = &LPOPSpecs{}
	case BLPOP:
		specs = &BLPOPSpecs{}
	case WAIT:
		specs = &WAITSpecs{}
	case SUBSCRIBE:
		specs = &SUBSCRIBESpecs{}
	case UNSUBSCRIBE:
		specs = &UNSUBSCRIBESpecs{}
	case QUIT:
		specs = &QUITSpecs{}
	case PUBLISH:
		specs = &PUBLISHSpecs{}
	case ACL_WHOAMI:
		specs = &ACL_WHOAMISpecs{}
	case ACL_GETUSER:
		specs = &ACL_GETUSERSpecs{}
	case ACL_SETUSER:
		specs = &ACL_SETUSERSpecs{}
	case AUTH:
		specs = &AUTHSpecs{}
	case ZADD:
		specs = &ZADDSpecs{}
	case ZRANK:
		specs = &ZRANKSpecs{}
	case ZRANGE:
		specs = &ZRANGESpecs{}
	case ZCARD:
		specs = &ZCARDSpecs{}
	case ZSCORE:
		specs = &ZSCORESpecs{}
	case ZREM:
		specs = &ZREMSpecs{}
	case WATCH:
		specs = &WATCHSpecs{}
	case UNWATCH:
		specs = &UNWATCHSpecs{}
	case GEOADD:
		specs = &GEOADDSpecs{}
	case GEOPOS:
		specs = &GEOPOSSpecs{}
	}
	if specs == nil {
		return
	}
	if vp, ok := specs.(FullParser); ok {
		vp.Parse(args...)
		return
	}
	var consumed int
	if vp, ok := specs.(ScalerParser); ok {
		consumed, err = vp.ParseScaler(args...)
		if err != nil {
			return nil, err
		}
	}
	if vp, ok := specs.(FlagParser); ok {
		err = vp.ParseFlags(args[consumed:]...)
		if err != nil {
			return nil, err
		}
	}
	if vp, ok := specs.(VariadicTailParser); ok {
		err := vp.ParseTail(args[consumed:]...)
		if err != nil {
			return nil, err
		}
	}
	return
}
